### ISSUE TITLE
Opcion Enviar

### ISSUE THREAD

**Issue by fpenovi** [fpenovi/MetalZcurra#1]
![issue](https://cloud.githubusercontent.com/assets/19509087/18234742/a94201d8-72e4-11e6-9add-60c50ac652a1.png)

Aplicar un protocolo para reconocer las opciones y no imprimirlas en el servidor.
Para discriminar un mensaje de un comando propongo que se a los comandos se les agregue "/*" adelante.

**Comment by chelalita** [comment]
googleame
